export const FETCH_CODELIST_FUNSKJON = 'FETCH_CODELIST_FUNSKJON';
export const FETCH_SUBMISSION = 'FETCH_SUBMISSION';
export const FETCH_SELECTED_FORM = 'FETCH_SELECTED_FORM';
export const UPDATE_SELECTED_FORM = 'UPDATE_SELECTED_FORM';
export const SAVE_SELECTED_FORM = 'SAVE_SELECTED_FORM';