export const FETCH_COMMITS = 'FETCH_COMMITS';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_SELECTED_FORM = 'UPDATE_SELECTED_FORM';
export const FETCH_SUBMISSION = 'FETCH_SUBMISSION';
