export const FETCH_SUBMISSION = 'FETCH_SUBMISSION';
export const FETCH_SELECTED_FORM = 'FETCH_SELECTED_FORM';
export const UPDATE_SELECTED_FORM = 'UPDATE_SELECTED_FORM';
export const SAVE_SELECTED_FORM = 'SAVE_SELECTED_FORM';
export const UPDATE_SNACKBAR_MESSAGE = 'UPDATE_SNACKBAR_MESSAGE';
export const UPDATE_SNACKBAR_VISIBLE = 'UPDATE_SNACKBAR_VISIBLE';
export const UPDATE_SNACKBAR_LASTINIT = 'UPDATE_SNACKBAR_LASTINIT';
export const UPDATE_IS_SIGNED_IN = 'UPDATE_IS_SIGNED_IN';